name: Terraform CI

on:
  push:


defaults:
  run:
    shell: bash
    working-directory: ./test

# concurrency:
#   group: ${{ github.action == 'terraform-automation' }}
#   cancel-in-progress: true

jobs:


    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@main


      - name: Set up Go For Terratest
        uses: actions/setup-go@v2

      - name: Setup Dependencies
        run:  go get -v -t -d && go mod tidy

      - name: Test
        run: go test -tags gcp -timeout 30m -p 1
